### ISSUE TITLE
Manifests

### ISSUE THREAD

**Issue by lgmoneda** [CodeClub/webdev-curriculum#74] opened 2016-05-18 20:23 UTC
Did i messed the manifests again? The projects page ins't reflecting what i was expecting from the last manifests i've pushed. Could you check it? Thanks!

**Comment by rik-cross** [comment] 2016-05-18 21:02
Hi @lgmoneda,
The 'cat-python' and 'cat-html' labels...

![screen shot 2016-05-18 at 22 01 16](https://cloud.githubusercontent.com/assets/18461167/15374838/1bd2e95c-1d44-11e6-9101-63f35d509a9a.png)

...are because of the `"category": "x"` line in the manifests, which I've now removed. See:

https://github.com/CodeClub/python-curriculum/commit/5eadc4872681860149d876b8eaa3e718b08b69ed
https://github.com/CodeClub/webdev-curriculum/commit/6ee40a3d4c763184f3e99e89f5e947ff4f0a1ac6
https://github.com/CodeClub/webdev-curriculum/commit/0533ae7728ec4432c962000226eb0a9980a08e8e

I've also noticed that the site hasn't been rebuilt since your latest updates, so the changes I've just made  should have triggered a rebuild.

**Comment by rik-cross** [comment] 2016-05-19 08:25
I've also just noticed that a couple of the projects had the frontmatter tags translated:

![screen shot 2016-05-19 at 09 05 22](https://cloud.githubusercontent.com/assets/18461167/15386669/0c4959be-1da1-11e6-9b57-65b6436d88d1.png)

I've translated them back (see https://github.com/CodeClub/webdev-curriculum/commit/5a0b69ea9b681e6ddcfa9f9ffa5417ad88680bd0). The changes should be live within 24 hours.

**Comment by rik-cross** [comment] 2016-05-19 11:02
I'll close this now, as the issue is fixed.

**Closed by rik-cross** 2016-05-19 11:02 UTC

**Comment by rik-cross** [comment] 2016-05-20 07:25
@lgmoneda the fixed site is now live :)
